### ISSUE TITLE
请问王老师，在您最近更新的19年结果列表中的 MLSLNet是哪篇论文？ 

### ISSUE THREAD

**Issue by Xiaoqi-Zhao-DLUT** [wenguanwang/SODsurvey#6]

**Comment by wenguanwang** [comment]
![reference](https://user-images.githubusercontent.com/20334457/65369852-928b8180-dc63-11e9-83ba-409b288f7adb.png)

**Comment by wenguanwang** [comment]
感谢关注。论文还没有同步在arxiv更新。

**Comment by Xiaoqi-Zhao-DLUT** [comment]
另外您这篇论文，An Iterative and Cooperative Top-down and Bottom-up Inference Network for Salient Object Detection的saliency map我看已经在你的主页上公布了，我下来看应该是在resnet50上的结果吧？ 记得在您的论文中也对vgg16进行了测试，可否也上传下对应的sm。 十分感谢！

**Comment by cleverZhaoXiaoqi** [comment]
> 感谢关注。论文还没有同步在arxiv更新。

**Comment by wenguanwang** [comment]
@cleverZhaoXiaoqi 是的。我最近有时间的时候整理一下。
