### ISSUE TITLE
Some of statics in the table is different with original paper report.

### ISSUE THREAD

**Issue by vandesa003** [wenguanwang/SODsurvey#7]
Hi @wenguanwang , thanks for your great work and a lot of solid previous works. But I found that in the mentioned table, some results are different with original paper. For example, BASNet, they reported as follows:
![quan](https://user-images.githubusercontent.com/10252812/70387229-6ae3c400-19dd-11ea-83f4-e579e31c089c.png)
While in your table, the results are totally different. Is that because you re-run the evaluation matrics rather than using their report or some other reasons?

**Comment by wenguanwang** [comment]
@vandesa003, thanks for your interest. I found different authors use different metrics, for example, weighted average of F-score or the maximum F-score. In addition, if you use different sizes of the input saliency maps, or different intervals during thresholding the F scores, you can get different results. Even for a same metrics, the implementations used in different research groups are actually different. If you implement the F-score by yourself, we can found there may exit different ways, causing different results. Such issues hurt the development of this community. Therefore, one of the major goals of this work is to provide a unified, and relatively fair way for benchmarking all the SOD methods.  Thanks.

**Comment by vandesa003** [comment]
@wenguanwang Noted with thanks!
