### ISSUE TITLE
您好王学长，您提供的百度云盘DUT-OMROM这个目录下的GT只有1600张缺了4000多张图

### ISSUE THREAD

**Issue by StormArcher** [wenguanwang/SODsurvey#8]
您好王学长，我下载了您提供的百度云盘提供的内容
发现在DUT-OMROM这个目录下的GT只有1600张应该是5168张真值，
能否提供下完整的？

**Comment by wenguanwang** [comment]
@zhujinchao123 在赶ddl。过后回复。

**Comment by wenguanwang** [comment]
@zhujinchao123 
在这里。后面会更新一下原来的链接。
链接：https://pan.baidu.com/s/1hE92zWzwBHVY_k8eJ6oq9w 
提取码：vae5
